// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from LibGraphle/graphle/algorithm.

#pragma once

#include <algorithm/strongly_connected_components.hpp>
