// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from LibGraphle/graphle.

#pragma once

#include <algorithm.hpp>
#include <algorithm/strongly_connected_components.hpp>
#include <common.hpp>
#include <doxygen.hpp>
#include <graph.hpp>
#include <graph/constraint_debug_helper.hpp>
#include <graph/edges.hpp>
#include <graph/graph.hpp>
#include <graph/graph_concepts.hpp>
#include <meta.hpp>
#include <meta/always_false.hpp>
#include <meta/const_pointer.hpp>
#include <meta/if_constexpr.hpp>
#include <meta/is_template.hpp>
#include <meta/type_list.hpp>
#include <meta/value.hpp>
#include <search.hpp>
#include <search/breadth_first_search.hpp>
#include <search/depth_first_search.hpp>
#include <search/search_impl.hpp>
#include <search/visitor.hpp>
#include <storage.hpp>
#include <storage/default_storage_provider.hpp>
#include <storage/storage_provider.hpp>
#include <storage/storage_provider_helpers.hpp>
#include <utility.hpp>
#include <utility/degree.hpp>
#include <utility/detail/functional.hpp>
#include <utility/detail/range_utils.hpp>
#include <utility/detail/storage_utils.hpp>
#include <utility/detail/vec_of_vecs_output_iterator.hpp>
#include <views.hpp>
#include <views/duplicate_transposed_edges.hpp>
#include <views/edge_from_vertex.hpp>
#include <views/edge_perspective.hpp>
