// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from Graphle/graphle.

#pragma once

#include <algorithm.hpp>
#include <algorithm/strongly_connected_components.hpp>
#include <common.hpp>
#include <doxygen.hpp>
#include <graph.hpp>
#include <graph/constraint_debug_helper.hpp>
#include <graph/graph.hpp>
#include <graph/graph_concepts.hpp>
#include <graph/vertex_compare.hpp>
#include <meta.hpp>
#include <meta/concepts.hpp>
#include <meta/const_pointer.hpp>
#include <meta/if_constexpr.hpp>
#include <meta/trait_definition.hpp>
#include <meta/tuple.hpp>
#include <meta/type_list.hpp>
#include <meta/value.hpp>
#include <search.hpp>
#include <search/breadth_first_search.hpp>
#include <search/depth_first_search.hpp>
#include <search/search_impl.hpp>
#include <search/visitor.hpp>
#include <storage.hpp>
#include <storage/default_storage_provider.hpp>
#include <storage/storage_provider.hpp>
#include <storage/storage_provider_helpers.hpp>
#include <utility.hpp>
#include <utility/edge_utils.hpp>
#include <utility/functional.hpp>
#include <utility/range_utils.hpp>
#include <utility/storage_utils.hpp>
#include <utility/vec_of_vecs_output_iterator.hpp>
#include <utility/vertex_utils.hpp>
#include <views.hpp>
#include <views/duplicate_transposed_edges.hpp>
#include <views/edge_from_vertex.hpp>
#include <views/edge_perspective.hpp>
#include <views/maybe_exists.hpp>
