// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from Graphle/graphle/meta.

#pragma once

#include <meta/concepts.hpp>
#include <meta/const_pointer.hpp>
#include <meta/if_constexpr.hpp>
#include <meta/tuple.hpp>
#include <meta/type_list.hpp>
#include <meta/value.hpp>
