// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from LibGraphle/graphle/storage.

#pragma once

#include <storage/default_storage_provider.hpp>
#include <storage/storage_provider.hpp>
#include <storage/storage_provider_helpers.hpp>
