// This file is automatically generated by CMake.
// Do not edit it, as your changes will be overwritten the next time CMake is run.
// This file includes headers from LibGraphle/libgraphle/views.

#pragma once

#include <views/duplicate_transposed_edges.hpp>
#include <views/edge_from_vertex.hpp>
#include <views/edge_perspective.hpp>
