name: Build & Run Tests (Windows | Clang)

on:
  push:
    branches: [ "master", "dev", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        # Note: build matrix split between run-tests-windows-msvc.yml and run-tests-windows-clang.yml
        #  so that we can generate separate badges for both of them.
        build_type: [Debug, Release]
        cxx_compiler: [clang-cl]
        include:
          - cxx_compiler: clang-cl
            dependencies: "visualstudio2022buildtools visualstudio2022-workload-vctools ninja llvm"
            generator: Ninja

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/out" >> "$GITHUB_OUTPUT"

    - name: Update / Install Toolchain
      run: choco upgrade ${{ matrix.dependencies }} -y

    - name: Create output directory
      run: mkdir out

    - name: Configure CMake
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      shell: cmd
      run: >
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat" &&
        cmake
        -G "${{ matrix.generator }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_C_COMPILER=${{ matrix.cxx_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }}
        -DGRAPHLE_TESTS=ON
        ../

    - name: Build
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
