name: Build & Run Tests (Linux)

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [Debug, Release]
        cxx_compiler: [clang, g++]

    steps:
    - uses: actions/checkout@v3

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/out" >> "$GITHUB_OUTPUT"

    - name: Update LLVM
      run: bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Update GCC
      run: sudo apt-get install g++

    - name: Create output directory
      run: mkdir out

    - name: Configure CMake
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      env:
        CC: ${{ matrix.cxx_compiler }}
        CXX: ${{ matrix.cxx_compiler }}
      run: >
        cmake
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DGRAPHLE_TESTS=ON
        ../

    - name: Build
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
